language: node_js
matrix:
  fast_finish: true
  include:
  - os: windows
    node_js: 10
  - os: osx
    node_js: 10
  - os: linux
    node_js: 10
    env:
    - CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- yarn lint
script:
- yarn dist
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
- yarn test
notifications:
  email: false
