language: node_js
os: osx
node_js: 10
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- yarn lint
script:
- yarn dist
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
- yarn test
notifications:
  email: false
